# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CONTENT_MANAGER:
            - ROLE_APP_ADMIN_PRODUCT_LIST
            - ROLE_APP_ADMIN_PRODUCT_VIEW
            - ROLE_APP_ADMIN_PRODUCT_EDIT
            - ROLE_APP_ADMIN_PRODUCT_CREATE
            - ROLE_APP_ADMIN_PRODUCT_DELETE
            - ROLE_APP_ADMIN_PRODUCT_IMAGE_LIST
            - ROLE_APP_ADMIN_PRODUCT_IMAGE_VIEW
            - ROLE_APP_ADMIN_PRODUCT_IMAGE_EDIT
            - ROLE_APP_ADMIN_PRODUCT_IMAGE_CREATE
            - ROLE_APP_ADMIN_PRODUCT_IMAGE_DELETE
            - ROLE_APP_ADMIN_PRODUCT_CATEGORY_LIST
            - ROLE_APP_ADMIN_PRODUCT_CATEGORY_VIEW
            - ROLE_APP_ADMIN_PRODUCT_CATEGORY_EDIT
            - ROLE_APP_ADMIN_PRODUCT_CATEGORY_CREATE
            - ROLE_APP_ADMIN_PRODUCT_CATEGORY_DELETE
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN
        ROLE_ADMIN:
            - ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_SONATA_ADMIN

    access_decision_manager:
            strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/my, role: ROLE_USER }
#        - { path: ^/basket, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
